export const ADD_MEASURE = 'ADD_MEASURE';
export const EDIT_MEASURE = 'EDIT_MEASURE';
export const DELETE_MEASURE = 'DELETE_MEASURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';

export const ADD_POLL = 'ADD_POLL';
export const EDIT_POLL = 'EDIT_POLL';
export const DELETE_POLL = 'DELETE_POLL';

export const ADD_QUESTION = 'ADD_QUESTION';
export const EDIT_QUESTION = 'EDIT_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';

export const SET_IS_ADMIN = 'SET_IS_ADMIN';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';

export const ADD_CATALOG_MEASURE = 'ADD_CATALOG_MEASURE';
export const ADD_CATALOG_MEASURES = 'ADD_CATALOG_MEASURES';
