export const ADD_MEASURE = 'ADD_MEASURE';
export const EDIT_MEASURE = 'EDIT_MEASURE';
export const DELETE_MEASURE = 'DELETE_MEASURE';

export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';

export const SET_IS_ADMIN = 'SET_IS_ADMIN';

export const NOTIFICATION_ADD = 'NOTIFICATION_ADD';
export const NOTIFICATION_DELETE = 'NOTIFICATION_DELETE';
